flowchart TD
subgraph bootefi_common[bootefi_common]
bootefi_common_start((start))
bootefi_common_start --> bootefi_common__cleanup_efi
bootefi_common__cleanup_efi["cleanup_efi<br/>type=ssh_cmd"]
bootefi_common__upload_efi["upload_efi<br/>type=upload_efi<br/>target_user=root<br/>target_ip={target_ip}<br/>target_path=/boot/efi/{binary_name}"]
bootefi_common__reboot_efi["reboot_efi<br/>type=reboot<br/>method=ssh<br/>target_user=root<br/>target_ip={target_ip}"]
bootefi_common__boot_efi["boot_efi<br/>type=uefi_shell_run"]
bootefi_common__pass["pass<br/>type=pass"]
bootefi_common__fail["fail<br/>type=fail"]
bootefi_common__cleanup_efi -->|label=ok| bootefi_common__upload_efi
bootefi_common__cleanup_efi -.->|timeout| bootefi_common__fail
bootefi_common__upload_efi -->|label=ok| bootefi_common__reboot_efi
bootefi_common__upload_efi -.->|timeout| bootefi_common__fail
bootefi_common__reboot_efi -->|label=ok| bootefi_common__boot_efi
bootefi_common__reboot_efi -.->|timeout| bootefi_common__fail
bootefi_common__boot_efi -->|label=ok| bootefi_common__pass
bootefi_common__boot_efi -.->|timeout| bootefi_common__fail
end
classDef pass fill:#dff0d8,stroke:#3c763d,stroke-width:1px;
classDef fail fill:#f2dede,stroke:#a94442,stroke-width:1px;
class bootefi_common__pass pass;
class bootefi_common__fail fail;
