flowchart TD
subgraph deploy_and_boot_test_efi[deploy_and_boot_test_efi]
deploy_and_boot_test_efi_start((start))
deploy_and_boot_test_efi_start --> deploy_and_boot_test_efi__upload_efi
deploy_and_boot_test_efi__upload_efi["upload_efi<br/>type=upload_efi<br/>target_user=root<br/>target_ip={target_ip}<br/>target_path=/efiboot/{target_binary_name}"]
deploy_and_boot_test_efi__reboot_efi["reboot_efi<br/>type=reboot<br/>method=ssh<br/>target_user=root<br/>target_ip={target_ip}"]
deploy_and_boot_test_efi__boot_efi["boot_efi<br/>type=boot_efi<br/>mode=test_efi"]
deploy_and_boot_test_efi__pass["pass<br/>type=pass"]
deploy_and_boot_test_efi__fail["fail<br/>type=fail"]
deploy_and_boot_test_efi__upload_efi -->|label=ok| deploy_and_boot_test_efi__reboot_efi
deploy_and_boot_test_efi__upload_efi -.->|timeout| deploy_and_boot_test_efi__fail
deploy_and_boot_test_efi__reboot_efi -->|label=ok| deploy_and_boot_test_efi__boot_efi
deploy_and_boot_test_efi__reboot_efi -.->|timeout| deploy_and_boot_test_efi__fail
deploy_and_boot_test_efi__boot_efi -->|label=ok| deploy_and_boot_test_efi__pass
deploy_and_boot_test_efi__boot_efi -.->|timeout| deploy_and_boot_test_efi__fail
end

classDef pass fill:#6cc644,stroke:#2c7a2c,color:#fff;
classDef fail fill:#d73a49,stroke:#7a1f25,color:#fff;
class deploy_and_boot_test_efi__pass pass;
class deploy_and_boot_test_efi__fail fail;
