flowchart TD
subgraph vm_qemu_virtio[vm-qemu-virtio]
vm_qemu_virtio_start((start))
vm_qemu_virtio_start --> vm_qemu_virtio__set_vm_wait_boot_alias
vm_qemu_virtio__set_vm_wait_boot_alias["set_vm_wait_boot_alias<br/>type=set_overrides"]
vm_qemu_virtio__run_vm_common["run_vm_common<br/>type=call_chain<br/>chain=vm_common<br/>chain_file=/home/hlyytine/autopilot/chains/vm_common.json"]
vm_qemu_virtio__pass["pass<br/>type=pass"]
vm_qemu_virtio__fail["fail<br/>type=fail"]
vm_qemu_virtio__set_vm_wait_boot_alias -->|label=ok| vm_qemu_virtio__run_vm_common
vm_qemu_virtio__set_vm_wait_boot_alias -.->|timeout| vm_qemu_virtio__fail
vm_qemu_virtio__run_vm_common -->|label=pass| vm_qemu_virtio__pass
vm_qemu_virtio__run_vm_common -->|label=fail| vm_qemu_virtio__fail
vm_qemu_virtio__run_vm_common -.->|timeout| vm_qemu_virtio__fail
end
classDef pass fill:#dff0d8,stroke:#3c763d,stroke-width:1px;
classDef fail fill:#f2dede,stroke:#a94442,stroke-width:1px;
class vm_qemu_virtio__pass pass;
class vm_qemu_virtio__fail fail;
